development:
  github:
    oauth_uri: https://github.com/login/oauth/authorize
    access_token_url: https://github.com/login/oauth/access_token
    # 获取 github 用户信息 url // eg: https://api.github.com/user?access_token=******&scope=&token_type=bearer
    user_url: https://api.github.com/user
    redirect_uri: http://localhost:3000/example/
    client_id: 00b6c38e8db6913a5017
    client_secret: 65dc13996e41df5ad57384e84d309fa88a0eb6bf
  gitee: 
    # https://gitee.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code&scope=user_info%20projects%20pull_requests get
    # https://gitee.com/oauth/token?grant_type=authorization_code&code={code}&client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret} post
    access_token_url: https://gitee.com/oauth/token
    redirect_uri: http://localhost:3000/example/
    user_url: https://gitee.com/api/v5/user
    client_id: 39aefd1833104e626a11eedef270650e6722a07e5ba3d5f7aeade645b9d5f3f8
    client_secret: 474d5b65d0a9348213c4c5f43185a555ab01871d7afaae2f955861522f9f983c