development:
  github:
    oauth_uri: https://github.com/login/oauth/authorize
    access_token_url: https://github.com/login/oauth/access_token
    # 获取 github 用户信息 url // eg: https://api.github.com/user?access_token=******&scope=&token_type=bearer
    user_url: https://api.github.com/user
    redirect_uri: http://biaochenxuying.cn/
    client_id:
    client_secret:
